# This file contains configuration settings for the devdocs website.
# Each setting is available on pages using Liquid {{ site.<config key> }}. For example, {{ site.title }}.
# For more details about available options and defaults, refer to https://jekyllrb.com/docs/configuration/
#
title: OpenMage LTS Developer Documentation
logo: DevDocs
description: OpenMage LTS Developer Documentation.

# the base protocol and domain
url: https://www.openmage.org/devdocs

# Site theme. https://jekyllrb.com/docs/themes/
theme: devdocs

# Base url that forms 
baseurl: ""

# Specific settings for different scopes.
#
defaults:

  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
      github_repo: https://github.com/OpenMage/devdocs/
      github_files: https://github.com/OpenMage/devdocs/blob/master/
      # Enables the 'Edit this page on GitHub' appearences on pages
      github_link: true
      # Enables the 'Give us feedback' appearences on pages
      feedback_link: true
  -
    scope:
      path: guides/m1x
    values:
      layout: null

  -
    scope:
      path: mftf/2.2
    values:
      group: magento-functional-testing-framework-guide
      functional_areas:
        - Test

  -
    scope:
      path: mftf/2.3
    values:
      group: magento-functional-testing-framework-guide-2_3
      functional_areas:
        - Test

##########################
# Plugins and extensions #
##########################
#
# For more details about plugins, refer to https://jekyllrb.com/docs/plugins/
# To learn more about particular plugin, find it by name on GitHub.
# This list doesn't include custom plugins.
#
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-titles-from-headings

# Settings for the jekyll-titles-from-headings plugin.
# For more details about the plugin, refer to https://github.com/benbalter/jekyll-titles-from-headings
#
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

# kramdown parser settings (extended Markdown to HTML parser). For more details about available options, refer to https://kramdown.gettalong.org/converter/html.html
#
kramdown:
  toc_levels: 2..3
  syntax_highlighter_opts:
    css_class: highlighter

# LiveReload monitors changes in the file system and refreshes browser when Jekyll is in serving mode.
# http://livereload.com/
#
livereload: true

# Search engine settings. For more details, refer to https://github.com/algolia/jekyll-algolia
#
algolia:
  application_id: E642SEDTHL
  index_name: devdocs
  api_key: d2d0f33ab73e291ef8d88d8b565e754c
  files_to_exclude:
    - guides/m1x/**/*.html
    - guides/m1x/**/*.md
    - swagger
    - redoc

google:
  analytics: UA-66243208-1

# Toggles the _plugin/html-check-hook.rb script that checks links in the generated HTML
#
check_links: true

#############
# Variables #
#############
#
# 1.x variables
m1xgdeurl: /guides/m1x/
m1xgithuburl: https://github.com/OpenMage/devdocs/blob/master/

##########
# Ignore #
##########
#
# The path patterns excluded during site generation
#
exclude:
  - scss
  - bin
  - node_modules
  - vendor
  - .git
  - .idea
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - Rakefile
  - rakelib
  - README.md
  - _plugins
